item {
	name: "nike"
	id: 1
}

item {
	name: "jordans"
	id: 2
}

item {
	name: "puma"
	id: 3
}

item {
	name: "quicksilver"
	id: 4
}

item {
	name: "adi"
	id: 5
}

item {
	name: "kappa"
	id: 6
}